# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Contractor' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge',
      'DevSupport',
      'RCTAnimation',
      'RCTActionSheet',
      'RCTBlob',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'ART'
    ]

    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
    pod 'RNScreens', :path => '../node_modules/react-native-screens'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'Interactable', :path => '../node_modules/react-native-interactable'

end
